import { useState } from 'react';
import { Head, Link } from '@inertiajs/react';
import BrandLogo from '../Components/BrandLogo';
import ProviderLogo from '../Components/ProviderLogo';

const workflow = [
    ['01', 'Understand earnings', 'See customer charges, verified provider fees and expenses together.'],
    ['02', 'Reconcile settlements', 'Know when expected settlements and received money do not match.'],
    ['03', 'Close the day', 'Enter actual balances and identify differences before closing.'],
];

export default function Welcome({ auth }) {
    const [menuOpen, setMenuOpen] = useState(false);

    return <><Head title="Know what your POS business earns" /><div className="public-site">
        <header className="public-header"><div className="public-nav-wrap"><Link href="/" className="public-brand" aria-label="POSPilot home"><BrandLogo /></Link>
            <button type="button" className="public-menu-toggle" aria-expanded={menuOpen} aria-controls="public-nav" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}><span /><span /><span /></button>
            <nav id="public-nav" className={`public-nav ${menuOpen ? 'public-nav-open' : ''}`} aria-label="Main navigation"><a href="#product" onClick={() => setMenuOpen(false)}>Product</a><a href="#security" onClick={() => setMenuOpen(false)}>Security</a><a href="#providers" onClick={() => setMenuOpen(false)}>Providers</a><Link href="/demo" onClick={() => setMenuOpen(false)}>View demo</Link>{auth?.user ? <Link className="public-nav-primary" href="/dashboard">Open workspace</Link> : <><Link href="/login" onClick={() => setMenuOpen(false)}>Sign in</Link><Link className="public-nav-primary" href="/register" onClick={() => setMenuOpen(false)}>Create account</Link></>}</nav>
        </div></header>
        <main>
            <section className="public-hero"><div className="public-hero-inner"><div className="public-hero-copy"><p className="public-kicker"><span /> FINANCIAL CLARITY FOR POS BUSINESSES</p><h1>Know what you <em>really earned.</em></h1><p className="public-hero-description">Bring transaction records and provider settlements together. See customer charges, fees and differences clearly, without treating transaction value as profit.</p><div className="public-hero-actions">{!auth?.user && <Link className="public-button public-button-primary" href="/register">Create your account <span aria-hidden="true">→</span></Link>}<Link className="public-button public-button-secondary" href={auth?.user ? '/dashboard' : '/login'}>{auth?.user ? 'Open your workspace' : 'Sign in'}</Link></div><p className="public-hero-note">Estimates are clearly marked when provider fee data is incomplete.</p></div>
                <section className="workflow-card" aria-label="How POSPilot helps"><p className="public-kicker">A CLEARER WAY TO RUN YOUR DAY</p><h2>Know where every naira stands.</h2><div className="workflow-list">{workflow.map(([number, title, text]) => <article className="workflow-item" key={number}><span className="workflow-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div><span className="workflow-check" aria-hidden="true">✓</span></article>)}</div><div className="workflow-footnote"><span aria-hidden="true">₦</span><p>Keep estimates and verified figures easy to tell apart.</p></div></section></div></section>
            <section className="public-section" id="product"><div className="public-section-heading"><p className="public-kicker">BUILT AROUND YOUR DAILY WORK</p><h2>Clarity from first transaction to close.</h2><p>Useful records and checks, together in one place.</p></div><div className="public-capabilities">{[['01', 'Know your money', 'Understand earnings with customer charges, verified provider fees and recorded expenses together.'], ['02', 'Reconcile', 'Compare expected settlements with what arrived and find differences that need a closer look.'], ['03', 'Close the day', 'Record actual cash and provider balances, then review the difference before you finish.']].map(([number, title, text]) => <article className="capability-card" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
            <section className="trust-section" id="security"><div className="trust-copy"><p className="public-kicker">YOUR RECORDS DESERVE CARE</p><h2>Clear records. Thoughtful access.</h2><p>POSPilot is designed to help organize your business information while keeping sensitive provider access in your hands.</p></div><div className="trust-points"><p><span>✓</span><strong>Your provider password stays yours.</strong></p><p><span>✓</span><strong>POSPilot will never ask for your transaction PIN or OTP.</strong></p><p><span>✓</span><strong>Provider connections use approved integration credentials where supported.</strong></p></div></section>
            <section className="provider-section" id="providers"><div><p className="public-kicker">EMAIL STATEMENTS</p><h2>Bring your POS records together.</h2><p>Connect Gmail to check recent provider statements. POSPilot imports only activity it can confidently identify as POS transactions; unclear rows wait for your review.</p></div><div className="provider-cards"><article className="provider-card provider-card-active"><ProviderLogo provider="OPay" size="lg" /><div><strong>OPay</strong><p>Email statement review</p></div><span className="provider-state-tag">Supported source</span></article><article className="provider-card"><ProviderLogo provider="Moniepoint" size="lg" /><div><strong>Moniepoint</strong><p>Email statement review</p></div><span className="provider-state-tag provider-state-muted">Supported source</span></article><article className="provider-card"><ProviderLogo provider="PalmPay" size="lg" /><div><strong>PalmPay</strong><p>Email statement review</p></div><span className="provider-state-tag provider-state-muted">Supported source</span></article></div></section>
            <section className="public-final-cta"><p className="public-kicker">MAKE EVERY CLOSE COUNT</p><h2>Know what your POS business really earns.</h2><p>Bring your daily activity and settlement picture into focus.</p><div className="public-hero-actions">{!auth?.user && <Link className="public-button public-button-primary" href="/register">Create account <span aria-hidden="true">→</span></Link>}<Link className="public-button public-button-light" href={auth?.user ? '/dashboard' : '/login'}>{auth?.user ? 'Open workspace' : 'Sign in'}</Link></div></section>
        </main>
        <footer className="public-footer"><div className="public-footer-inner"><div className="public-footer-brand"><Link href="/" className="public-brand" aria-label="POSPilot home"><BrandLogo /></Link><p>Financial clarity for POS businesses.</p></div><nav aria-label="Footer navigation"><a href="#product">Product</a><a href="#security">Security</a><Link href="/login">Sign in</Link><Link href="/register">Create account</Link></nav><small>© 2026 POSPilot</small></div></footer>
    </div></>;
}
