<?php

return [
    'ingestion_source_priority' => [
        'provider_api' => 500,
        'provider_webhook' => 400,
        'provider_statement' => 300,
        'calculated' => 200,
        'manual' => 100,
        'demo' => 0,
    ],
    'provider_capabilities' => [
        'opay' => [
            'direct_connection' => 'requires_provider_access',
            'connector_implementation' => 'planned',
            'connection_test' => 'planned',
            'csv_transaction_import' => 'supported',
            'csv_settlement_import' => 'supported',
            'api_transaction_sync' => 'documented',
            'webhook_transactions' => 'unverified',
            'settlement_sync' => 'unverified',
            'balance_sync' => 'planned',
            'terminal_mapping' => 'documented',
            'historical_sync' => 'documented',
            'provider_fee' => 'unverified',
            'sandbox' => 'unverified',
            'live_tested' => 'unverified',
        ],
        'moniepoint' => [
            'direct_connection' => 'requires_provider_access',
            'connector_implementation' => 'planned',
            'connection_test' => 'supported',
            'csv_transaction_import' => 'supported',
            'csv_settlement_import' => 'supported',
            'api_transaction_sync' => 'planned',
            'webhook_transactions' => 'unverified',
            'settlement_sync' => 'unverified',
            'balance_sync' => 'unverified',
            'terminal_mapping' => 'unverified',
            'historical_sync' => 'unverified',
            'provider_fee' => 'unverified',
            'sandbox' => 'documented',
            'live_tested' => 'unverified',
        ],
        'palmpay' => [
            'direct_connection' => 'coming_later',
            'csv_transaction_import' => 'supported',
            'csv_settlement_import' => 'supported',
            'api_transaction_sync' => 'unsupported',
            'webhook_transactions' => 'unsupported',
            'settlement_sync' => 'unsupported',
            'balance_sync' => 'unverified',
            'terminal_mapping' => 'unverified',
            'historical_sync' => 'unsupported',
            'provider_fee' => 'unverified',
            'sandbox' => 'unverified',
            'live_tested' => 'unverified',
        ],
        'other' => ['csv_transaction_import' => 'supported', 'csv_settlement_import' => 'supported', 'api_transaction_sync' => 'unavailable', 'webhook_transactions' => 'unavailable', 'settlement_sync' => 'unavailable', 'balance_sync' => 'unavailable'],
    ],
    'daily_closing' => [
        'small_variance_threshold' => '100.00',
        'review_variance_threshold' => '1000.00',
        'transaction_effects' => [
            'withdrawal' => ['cash' => '-amount', 'electronic' => 'net'],
            'deposit' => ['cash' => 'amount', 'electronic' => '-net'],
            'transfer' => ['cash' => 'amount', 'electronic' => '-net'],
            'payment' => ['cash' => 'amount', 'electronic' => '-net'],
        ],
    ],
];
